# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: priyankgupta
  password: 
  reaping_frequency: 10
  pool: 20

development:
  <<: *defaults
  database: college_portal_dev
  host: localhost
  port: 5432
